### ISSUE TITLE
New name for the project

### ISSUE THREAD

**Issue by Aenyhm** [Codazus/YAQB#1]
The name `YAQB` is already assigned for [a similar library](https://packagist.org/packages/victorium/yaqb). We have to find another one.

Feel free to add your ideas here.

Here are some keywords I found so far related to this project:
* Language, Query, Abstract, Data
* Builder, Maker, Layer, Creator, Generator
* Fluent, Sequence, API

**Comment by DjLeChuck** [comment]
SQB? (Simple/SQL Query Builder)

L'écriture de l'API se veut **SIMPLE** et **INTUITIVE**. On écrit la requête de manière **NATURELLE**.

**Comment by DjLeChuck** [comment]
New name: siqubu (**si**mple **qu**ery **bu**ilder)
